image: debian:9

stages:
  - init
  - compile

Install dependencies:
  stage: init
  script:
   - apt-get update -qy
   - apt-get install -y build-essential libsqlite3-dev

make:
  stage: compile
  script:
   - make
